## Reference: https://github.com/amannn/action-semantic-pull-request
---
name: "Lint PR Title"
on:
  pull_request_target:
    types: [opened, reopened, edited, synchronize]
jobs:
  lint_pr_title:
    permissions:
      contents: read
      pull-requests: read
      statuses: write
    uses: github/ospo-reusable-workflows/.github/workflows/pr-title.yaml@465a8648d16d710aab3e224ea0eb5fca579e6e4b
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
